test

diff --git a/.github/workflows/build-mudlet-win.yml b/.github/workflows/build-mudlet-win.yml
--- a/.github/workflows/build-mudlet-win.yml
+++ b/.github/workflows/build-mudlet-win.yml
@@ -84,36 +84,6 @@ jobs:
       shell: msys2 {0}
       run: $GITHUB_WORKSPACE/CI/package-mudlet-for-windows.sh
 
-    - name: (Windows) Login to Azure
-      uses: azure/login@v2
-      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
-      with:
-        creds: ${{ secrets.AZURE_CREDENTIALS }}
-
-    - name: Get Azure access token for code signing
-      shell: pwsh
-      if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
-      run: |
-        $token = (az account get-access-token --resource https://codesigning.azure.net | ConvertFrom-Json).accessToken
-        "::add-mask::$token"
-        "AZURE_ACCESS_TOKEN=$token" | Add-Content -Path $env:GITHUB_ENV
-
-    - name: (Windows) Deploy
-      shell: msys2 {0}
-      env:
-        DBLSQD_USER: ${{secrets.DBLSQD_USER}}
-        DBLSQD_PASS: ${{secrets.DBLSQD_PASS}}
-        DEPLOY_KEY_PASS: ${{secrets.DEPLOY_KEY_PASS}}
-        DEPLOY_SSH_KEY: ${{secrets.DEPLOY_SSH_KEY}}
-        DEPLOY_PATH: ${{secrets.DEPLOY_PATH}}
-        AZURE_ACCESS_TOKEN: ${{ env.AZURE_ACCESS_TOKEN }}
-        GITHUB_REPO_NAME: ${{ github.repository }}
-        GITHUB_REPO_TAG: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
-        GITHUB_SCHEDULED_BUILD: ${{ github.event_name == 'schedule' || github.event.inputs.scheduled == 'true' }}
-        GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
-        GITHUB_PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
-      run: $GITHUB_WORKSPACE/CI/deploy-mudlet-for-windows.sh
-
     - name: Upload packaged Mudlet
       uses: actions/upload-artifact@v4
       if: env.UPLOAD_FILENAME
@@ -153,29 +123,15 @@ jobs:
         TESTS_DIRECTORY: ${{github.workspace}}/src/mudlet-lua/tests
         QUIT_MUDLET_AFTER_TESTS: 'true'
 
-
-
-    - name: Submit to make.mudlet.org
-      if: env.UPLOAD_FILENAME
+    - name: Passed Lua tests
+      if: matrix.buildname == 'windows64' || matrix.buildname == 'windows32'
       run: |
-        $uri = "https://make.mudlet.org/snapshots/gha_queue.php?artifact_name=$($env:UPLOAD_FILENAME)&unzip=$($env:PARAM_UNZIP)"
-        try {
-          $response = Invoke-WebRequest -Uri $uri -Method Post -ErrorAction Stop
-          Write-Output "Submission successful"
-        }
-        catch {
-          $errorMessage = $_.Exception.Message
-          if ($errorMessage -like "*Artifact is not unique*") {
-            Write-Output "Info: Artifact was already submitted and is not unique. Continuing..."
-            exit 0
-          }
-          else {
-            Write-Error "An error occurred: $errorMessage"
-            exit 1
-          }
-        }
-      shell: pwsh
-
+        if [ -e /tmp/busted-tests-failed ]
+        then
+          echo "Lua tests failed - see the action called 'Run Lua tests' above for detailed output."
+          exit 1
+        fi
+        
     - name: Register Release
       shell: msys2 {0}
       if: env.PUBLIC_TEST_BUILD == 'true'
